package com.secondchance.service;

import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Call;
import com.twilio.type.PhoneNumber;
import com.twilio.type.Twiml;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;

@Service
public class TwilioService {

    @Value("${twilio.account.sid}")
    private String accountSid;

    @Value("${twilio.auth.token}")
    private String authToken;

    @Value("${twilio.phone.from}")
    private String fromPhone;

    @Value("${twilio.phone.to}")
    private String toPhone;

    @Value("${app.base.url}")
    private String appBaseUrl;

    @PostConstruct
    public void init() {
        if (!"default".equals(accountSid) && accountSid != null && !accountSid.isEmpty()) {
            Twilio.init(accountSid, authToken);
        }
    }

    public void makeEmergencyCall(String audioUrlPath) {
        String fullAudioUrl = appBaseUrl + audioUrlPath;

        // Twilio expects a valid TwiML XML string telling it what to do when the person answers the phone.
        // We are telling it to <Play> the MP3 generated by ElevenLabs.
        String twimlString = "<Response><Play>" + fullAudioUrl + "</Play></Response>";
        Twiml twiml = new Twiml(twimlString);

        Call call = Call.creator(
                new PhoneNumber(toPhone),
                new PhoneNumber(fromPhone),
                twiml
        ).create();

        System.out.println("Twilio Call Initiated! SID: " + call.getSid());
    }
}
