spring.application.name=SecondChance
spring.config.import=optional:classpath:application-secret.properties

twilio.account.sid=${TWILIO_ACCOUNT_SID:default}
twilio.auth.token=${TWILIO_AUTH_TOKEN:default}
twilio.phone.from=${TWILIO_PHONE_FROM:default}
twilio.phone.to=${TWILIO_PHONE_TO:default}
app.base.url=${APP_BASE_URL:http://localhost:8080}
